version: 2.1

orbs:
  python: circleci/python@1.2
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  main:
    jobs:
      - build-and-test



jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:13.12-browser'

    dependencies:
      pre:
        - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome.deb
        - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome

    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          command: |
            python3 -m venv env
            . env/bin/activate
            python3 -m pip install --upgrade pip
      - restore_cache:
          key: -v3-requirements-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements.txt
      - save_cache:
          key: -v3-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - store_artifacts:
          path: ~/AutoTrust_User_Testing_Workspace/artifacts
          destination: artifact-file
