version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  main:
    jobs:
      - build-and-test



jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:13.12-browser'
      steps:
        - browser-tools/install-chrome
        - browser-tools/install-chromedriver
        - run:
            command: |
              google-chrome --version
              chromedriver --version
            name: Check install

    steps:
      - checkout

      - run: python3 -m venv env
      - run: . env/bin/activate
      - run: python3 -m pip install --upgrade pip
      - run: pip install libcudart.so.11.0
      - run: pip install libcuda.so.1
      - restore_cache:
          key: -v3-requirements-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements.txt
      - save_cache:
          key: -v3-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run: behave

      - store_artifacts:
          path: root/AutoTrust_User_Testing_Workspace/artifacts
          destination: artifact-file
